exports.up = function(knex) {
  return knex.schema
    .createTable('users', table => {
      table.increments('id').primary()
      table.string('username', 50).notNullable().unique().comment('用户名')
      table.string('password', 255).notNullable().comment('密码(加密)')
      table.string('role', 20).defaultTo('user').comment('角色: admin-管理员, user-普通用户')
      table.timestamp('created_at').defaultTo(knex.fn.now())
      table.timestamp('updated_at').defaultTo(knex.fn.now())
    })
    .createTable('consumables', table => {
      table.increments('id').primary()
      table.string('product_code', 20).notNullable().unique().comment('产品编号(YYMMDD+四位序号)')
      table.string('name', 100).notNullable().comment('耗材名称')
      table.string('spec_model', 200).defaultTo('').comment('规格型号')
      table.integer('quantity').notNullable().defaultTo(0).comment('数量')
      table.string('unit', 20).notNullable().defaultTo('个').comment('单位')
      table.decimal('unit_price', 10, 2).notNullable().defaultTo(0).comment('单价')
      table.string('reporter', 50).notNullable().comment('提报人')
      table.timestamp('created_at').defaultTo(knex.fn.now())
      table.timestamp('updated_at').defaultTo(knex.fn.now())
      table.index('product_code', 'idx_product_code')
      table.index('created_at', 'idx_created_at')
    })
    .createTable('stock_in_records', table => {
      table.increments('id').primary()
      table.string('record_code', 20).notNullable().unique().comment('入库单号(RK+YYMMDD+四位序号)')
      table.string('supplier_name', 200).notNullable().comment('供货商名称')
      table.string('supplier_address', 500).defaultTo('').comment('供货商地址')
      table.string('contact_phone', 50).defaultTo('').comment('联系电话')
      table.string('contact_person', 50).defaultTo('').comment('联系人')
      table.string('delivery_person', 50).notNullable().comment('送货人')
      table.string('warehouse_manager', 50).notNullable().comment('库房负责人')
      table.date('stock_in_date').notNullable().comment('入库日期')
      table.decimal('total_amount', 12, 2).defaultTo(0).comment('总金额')
      table.integer('created_by').unsigned().notNullable().comment('创建人ID')
      table.timestamp('created_at').defaultTo(knex.fn.now())
      table.timestamp('updated_at').defaultTo(knex.fn.now())
      table.index('record_code', 'idx_record_code')
      table.index('stock_in_date', 'idx_stock_in_date')
      table.foreign('created_by').references('id').inTable('users').onDelete('RESTRICT')
    })
    .createTable('stock_in_items', table => {
      table.increments('id').primary()
      table.integer('stock_in_id').unsigned().notNullable().comment('入库单ID')
      table.integer('consumable_id').unsigned().notNullable().comment('耗材ID')
      table.integer('quantity').notNullable().comment('入库数量')
      table.decimal('unit_price', 10, 2).notNullable().comment('入库单价')
      table.decimal('total_price', 12, 2).notNullable().comment('入库总价')
      table.timestamp('created_at').defaultTo(knex.fn.now())
      table.foreign('stock_in_id').references('id').inTable('stock_in_records').onDelete('CASCADE')
      table.foreign('consumable_id').references('id').inTable('consumables').onDelete('RESTRICT')
    })
    .createTable('stock_out_records', table => {
      table.increments('id').primary()
      table.string('record_code', 20).notNullable().unique().comment('出库单号(CK+YYMMDD+四位序号)')
      table.date('stock_out_date').notNullable().comment('出库日期')
      table.string('recipient', 50).notNullable().comment('领用人')
      table.string('purpose', 200).defaultTo('').comment('用途说明')
      table.decimal('total_amount', 12, 2).defaultTo(0).comment('总金额')
      table.integer('created_by').unsigned().notNullable().comment('创建人ID')
      table.timestamp('created_at').defaultTo(knex.fn.now())
      table.timestamp('updated_at').defaultTo(knex.fn.now())
      table.index('record_code', 'idx_record_code')
      table.index('stock_out_date', 'idx_stock_out_date')
      table.foreign('created_by').references('id').inTable('users').onDelete('RESTRICT')
    })
    .createTable('stock_out_items', table => {
      table.increments('id').primary()
      table.integer('stock_out_id').unsigned().notNullable().comment('出库单ID')
      table.integer('consumable_id').unsigned().notNullable().comment('耗材ID')
      table.integer('quantity').notNullable().comment('出库数量')
      table.decimal('unit_price', 10, 2).notNullable().comment('出库单价')
      table.decimal('total_price', 12, 2).notNullable().comment('出库总价')
      table.timestamp('created_at').defaultTo(knex.fn.now())
      table.foreign('stock_out_id').references('id').inTable('stock_out_records').onDelete('CASCADE')
      table.foreign('consumable_id').references('id').inTable('consumables').onDelete('RESTRICT')
    })
}

exports.down = function(knex) {
  return knex.schema
    .dropTableIfExists('stock_out_items')
    .dropTableIfExists('stock_out_records')
    .dropTableIfExists('stock_in_items')
    .dropTableIfExists('stock_in_records')
    .dropTableIfExists('consumables')
    .dropTableIfExists('users')
}
